name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest  # ✅ GitHub-hosted runner with full internet access

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew :ObjectTrackingCamera:assembleDebug

    - name: List APK output (for verification)
      run: ls -R ObjectTrackingCamera/build/outputs/apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: ObjectTrackingCamera-debug-apk
        path: ObjectTrackingCamera/build/outputs/apk/debug/*.apk
